### PR TITLE
Untrack gulp dynamically generated files.

### PR DESCRIPTION
**Pull request by leebickmtu**
Untrack gulp dynamically generated files.
Fix gulp task dependancies.

### CODE REVIEW

**Comment by leebickmtu** [comment]
When you had the inability to stop or quit the app was the error this?

`events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/home/korbin/predix-seed/public/index-inline.css'
`

**Comment by leebickmtu** [comment]
I believe I fixed the issues you had. Please pull all changes again and test.

Also, just updating the .gitignore will not remove the files if they are already tracked. The files have to be explicitly removed from the repo in addition to adding to the .gitignore. That's why my first commit removed the files that I am also adding to the .gitignore.

**Comment by leebickmtu** [comment]
Added another gulp task order change. 'gulp dist' would fail on a fresh code checkout unless 'gulp' was run first. Added the 'compile:all' task to 'gulp dist'.

**Comment by gedesigntech** [comment]
Hello, and thanks for your corrections to our git and gulp setup.  I have been incrementally testing and merging the changes to the 'develop' branch.  We have reached similar solutions to the gulp tasks.  Your help is appreciated, thanks again!

**Comment by gedesigntech** [comment]
Additionally, the index-inline.css file has been temporarily placed back to tracked status relating to a sass compile issue that is being resolved.  The items in this pull request have all been addressed.  Thank you for contributing!

**Comment by leebickmtu** [comment]
The sass compile issue you have when you untrack index-inline.css is because you need to return the second 'gulp.src' in 'compile.sass.js'. Gulp executes tasks asynchronously. Returning the task allows gulp to have a handle to the task and use dependencies.

You added 'compile:sass' as a dependency for 'compile:index' from my pull request. But you didn't include the return so it's not working. My pull request is a complete unit. Inform me if you have problems and I will get it working.

Additionally, the proper Github workflow if to have me change my pull request to get it to where you are ready to pull it, instead of committing the changes yourself. That way credit is maintained.

**Comment by gedesigntech** [comment]
Thanks for your explanation, I returned 'return' in compile.sass.js and untracked index-inline.css again.
Btw, what is your opinion on making compile.index dependent on compile.sass?  I made it so because index.html uses index-inline.css which in turn, depends on index-inline.scss.
I agree with point on the proper Github workflow, thanks for bringing it up.  Please let me know what specific steps are appropriate (given the state of this PR and that of the 'develop' branch).  I'm glad to acknowledge your contribution.  Thank you.

**Pull request closed without merging**
