### PR TITLE
fix to make seed app work inside or outside of corporate network.

### PR DESCRIPTION
**Pull request by gstroup**
This will check if the user's "http_proxy" environment variable is set.  If so, will add a "proxy-agent" so the request can go through the corporate proxy server.  Uses http-proxy middleware instead of json-proxy middleware.

### CODE REVIEW

**Comment by AnirbanKundu** [comment]
:+1:

**Comment by gstroup** [comment]
Also fixes issue #23.  Any chance we can get this merged in?  Thanks!

**Comment by mdwragg** [comment]
One for @ek. I'm up for taking this change - can you please revert the sections where you've taken out dev UAA servers out though please? We can look at how best to configure them in the future but for now we can roll with how we were (also, it stops us taking on the PR easily as we'd have to revert this bit anyway...). Thanks Greg!

cc/ @ek @carlosfhernandez

**Comment by gstroup** [comment]
@mdwragg  Sure, I can do that.  Are you sure we want those internal URLs in there??  I don't think those should be in a public repo.  Could confuse customers.  But if you need them in there, I'll add them back for now.  Maybe we can remove them in the future??

**Comment by gstroup** [comment]
@ek @mdwragg I reverted back those sections in the connect.js file.  Should be good now.  Thanks.

**Comment by mdwragg** [comment]
Nice! Thanks :-) @ek - please take a look at @gstroup 's fine work when you get a chance.

Thanks for your help @gstroup - we appreciate it!

**Comment by vasanthid** [comment]
Please merge @gstroup's fix to Predix seed. Otherwise, we are facing lot of issues and wasting lot of time in Predix seed working using grunt serve.

**Comment by gstroup** [comment]
Thanks for merging!

**Comment by mdwragg** [comment]
👍 Sorry for the delay @gstroup, @ek has been so busy but @gedesigntech is always there to help :-)

**Comment by gedesigntech** [comment]
@gstroup Thank you for the proxy solution, Greg!

**Comment by mdwragg** [comment]
image

**Comment by mdwragg** [comment]
^^ Just for you @gstroup ;-)

**Comment by gstroup** [comment]
:) Haha, nice one!  I know you guys are busy.  Keep @ek slaving away on that fancy new seed app.

**Pull request merged**
