### PR TITLE
Ability to fetch user information from UAA

### PR DESCRIPTION
**Pull request by akshayeshenoi**
Added a middleware that fetches user information from the UAA instance using the access token and adds it to the `request` object. 

Currently, the seed supports only login and authentication. Many applications require user information after SSO login. The middleware adds the access token to the header and makes a GET request to the `uaaURL/userinfo` endpoint.

### CODE REVIEW

**Comment by gstroup** [comment]
Thanks for the PR!  This will be helpful.  At first glance, I'm thinking we should also expose a /userinfo endpoint in this app, so the browser can also get the user info.  (For instance, to display logged in user name.)  And I think we should move the logic out of app.js into your new user-info.js file, and expose that function as a true node middleware function.  Following the `function(req, res, next)` pattern.

**Comment by gstroup** [comment]
Looks better, thanks again!  Let me test a little bit, discuss with my team, then I'll merge in.  I actually needed to implement this anyway, and you saved me some work.  👍

**Comment by akshayeshenoi** [comment]
No problem :) 

I'll try to add a /userinfo route that will display the name of the user maybe. 
Or we could display it at the top right corner.

**Comment by gstroup** [comment]
I manually merged your change into the "develop" branch.  In the future, please make pull requests to develop, not master branch.  Anyway, thanks for your contribution!  Very helpful.  Soon, we'll be adding a login/logout visual component to the seed app.

**Comment by akshayeshenoi** [comment]
Happy to help!

About the logout functionality, does hitting the ```/logout``` URL work right now? I was never able to terminate a session without having to close the browser and reopen it.

Is it an issue with the Shared UAA session termination?

**Comment by gstroup** [comment]
Yes, the `/logout` URL is working for me right now.  I'm not using Shared UAA though.  I believe the Shared UAA is configured differently... if you terminate that session, then you'll terminate all your GE SSO sessions. (proxy, HR website, Jenkins, anything integrated in to SSO.)  For that reason, I'm guessing they don't want to really terminate the GE SSO session.  You would have to ask the Shared UAA support team for more info.

**Pull request closed without merging**
